### ISSUE TITLE
Crash on onActivityResult

### ISSUE THREAD

**Issue by markthom-as** [hieudole/react-native-paypal-integration#2]
When trying to incorporate this package into our project (RN 0.39), I received the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.bundle.id, PID: 22465
   java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:261)
       at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:627)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:135)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
       at com.bundle.id.MainActivity.onActivityResult(MainActivity.java:14)
       at android.app.Activity.dispatchActivityResult(Activity.java:6932)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
I'm not sure what I'm doing wrong, but I'm calling the module as such:
```
  presentConsentFlow() {
    return new P((resolve, reject) => {
      RNPayPal.profileSharing({
        clientId: this.app.config.paypalClientID,
        environment: RNPayPal.PRODUCTION,
        merchantName: '...',
        merchantPrivacyPolicyUri: 'https://...',
        merchantUserAgreementUri: 'http://...',
        scopes: [
          RNPayPal.SCOPE_FUTURE_PAYMENTS,
          RNPayPal.SCOPE_PROFILE, // Full Name, Birth Date, Time Zone, Locale, Language
          RNPayPal.SCOPE_PAYPAL_ATTRIBUTES, // Age Range, Account Status, Account Type, Account Creation Date
          RNPayPal.SCOPE_EMAIL, // Email
          // RNPayPal.SCOPE_ADDRESS, // Address
          // RNPayPal.SCOPE_PHONE // Telephone
        ]
      },
      (res, err) => {
        console.log(res);
        if (err) {
          reject(new Error(err));
        } else {
          resolve(res);
        }
      });
    });
  }
```
Any suggestions on how to fix this? Thanks!

**Comment by hieudole** [comment]
Hello markthom-as,

Can you try to clean up the build? (go to android folder then run: gradlew clean)

**Comment by markthom-as** [comment]
Thank for your reply - I tried cleaning and rebuilding, but I still get the same error

**Comment by hieudole** [comment]
The error caused by some changes in the new version of RN. See: https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35

I updated the code to fix this issue. Please install the latest version of this module. Thanks!
